### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by jwhitmarsh** [bogus34/bookshelf-schema#1]
Hey, firstly - really great plugin, it works excellently. 

As a potential enhancement, would you be interested in using ES6 to make benefit of true JS classes? I recently wanted to extend the BooleanField and ended up doing it via prototypical inheritance/extension which is not quite as neat as true class inheritance. 

I don't want to step on toes or anything, so this is definitely not a case of "you **should** do this", but more a case of would you, and if so would you be interested in help/collaboration?

**Comment by bogus34** [comment]
Hi James!
Glad you like it!

Personally I prefer Coffeescript but I may resort to ES6 if it'll bring some real benefits. 
AFAIK ES6 classes is just a sugar on top of normal ED5 prototype-based inheritance. Im I wrong?
I didn't check but I think you can import ES5 classes to a ES6 code and extend it.

And the second thought. I want to keep this plugin usable with ES5. So even if I rewrite it with ES6 I still will have to compile it down to ES5 with Babel.

BTW. What kind of extension to BooleanField you've done? Is it something worth to be added to plugin itself?

**Comment by jwhitmarsh** [comment]
Yeah you're right that it's just sugar, but it's quite nice sugar :) I didn't realise you could extend ES5 classes with it though - i'll have to check that and maybe refactor! 

You would have to transpile if you wanted it in ES5, but I'd ask why? Node LTS (4.x) supports (most of) ES6 out of the box - i'm running Bookshelf and Bk-Schema in ES6 without any transpilation. 

Here's the extension (it's in vanilla JS because we're not using CS):

```
'use strict';
let fields = require('bookshelf-schema/lib/fields');

/**
 * overload bookshelf-schema BooleanField
 */
function BooleanField() {
  fields.BooleanField.apply(this, arguments);
}

BooleanField.prototype = fields.BooleanField.prototype;

BooleanField.prototype.parse = function(attrs) {
  if (this.name in attrs && typeof attrs[this.name] === 'string') {
    attrs[this.name] = (attrs[this.name] === 'true');
    return;
  }

  if (this.name in attrs) {
    attrs[this.name] = Boolean(attrs[this.name]);
    return;
  }
};

BooleanField.prototype.format = function(attrs) {
  if (this.name in attrs && typeof attrs[this.name] === 'string') {
    attrs[this.name] = (attrs[this.name] === 'true');
    return;
  }

  if (this.name in attrs) {
    attrs[this.name] = Boolean(attrs[this.name]);
    return;
  }
};

exports.BooleanField = BooleanField;
```

It's to allow for string booleans - so `{isTrue: "true", isTrue: true}` will both pass correctly. It's important for my project, but it's a bit niche which is why I didn't submit it but please feel free to use it :) 

If this were ES6, I'd be able to do something like:

```
class BooleanField extends fields.BooleanField {
  /**
   * parse
   * @param  {Array} attrs model attributes array
   */
  parse(attrs) {
    if (this.name in attrs && typeof attrs[this.name] === 'string') {
      attrs[this.name] = (attrs[this.name] === 'true');
      return;
    }

    if (this.name in attrs) {
      attrs[this.name] = Boolean(attrs[this.name]);
      return;
    }
  }

  /**
   * format
   * @param  {Array} attrs model attributes array
   */
  format(attrs) {
    if (this.name in attrs && typeof attrs[this.name] === 'string') {
      attrs[this.name] = (attrs[this.name] === 'true');
      return;
    }

    if (this.name in attrs) {
      attrs[this.name] = Boolean(attrs[this.name]);
      return;
    }
  }
}

exports.BooleanField = BooleanField;
```

**Comment by jwhitmarsh** [comment]
And you are totally correct, you can extend ES5 classes in ES6 :) So I've just refactored my code to be ^ that second one!

**Comment by bogus34** [comment]
> You would have to transpile if you wanted it in ES5, but I'd ask why? Node LTS (4.x) supports (most > of) ES6 out of the box - i'm running Bookshelf and Bk-Schema in ES6 without any transpilation. 

Looks like Bookshelf supports node v0.12. But... Good point anyway. 

> It's to allow for string booleans - so {isTrue: "true", isTrue: true} will both pass correctly. It's important > for my project, but it's a bit niche which is why I didn't submit it but please feel free to use it :) 

I see. I feel somewhat uncomfortable converting string to boolean in that way.

Thanks for conversation!
