### ISSUE TITLE
EncryptedString.verify is always resolving

### ISSUE THREAD

**Issue by joakimbugge** [bogus34/bookshelf-schema#16]
I was a bit caught off guard by the way the `verify()` method for `EncryptedStringField` works. I expected it to either resolve the promise if the password is verified or reject it if not. I had to check the source to figure out that it actually always resolves (unless the hashing fails) and passes a boolean that says whether or not the verification is successful.

Would it be more intuitive if the method worked as in the following example?

```javascript
user.password.verify(value).then(() => {
  console.log('Successfully verified the password');
}).catch(error => {
  console.log('Failed to verify');
});
```

I mean, the hashing _should_ never fail. If it actually does, the password would not have been hashed in the first place (e.g. on user creation), and the verify method will not work anyway.

**Comment by bogus34** [comment]
I think about password.verify as of function that returns boolean. You suggest that it should throw an exception. Technically not, but rejecting a promise is almost like an exception, especially in async-await world. In my opinion, it's a bit over-reaction on just a not valid password :)
And seriously, I don't want to introduce that kind of backward-incompatible change without really strong necessity.
But probably I have to describe EncryptedString.verify method in documentation.
