### ISSUE TITLE
Example of chainable scope

### ISSUE THREAD

**Issue by niftylettuce** [bogus34/bookshelf-schema#2]
We should probably document this:

``` js
Scope('has_all_fields_set', () => {
  this
    .where('something', 'is not null')
    .where('something_else', 'is not null')
    .where('other_thing', 'is not null');
  }),
```

**Comment by bogus34** [comment]
Your code example is not actually a "chainable scope". It's just a regular use of query builder.

**Comment by niftylettuce** [comment]
I thought we should let people know they could do this though in the docs
