### ISSUE TITLE
Schema in es6 claases

### ISSUE THREAD

**Issue by roackb2** [bogus34/bookshelf-schema#9]
how should I make schema work in es6 classes?
I can not call `verify` on my `password` field, which is a `EncryptedStringField`

```javascript
class User extends bookshelf.Model {
    get schema() {
        return [
              StringField('username'),
              EncryptedStringField("password")
        ]
   }
}
```

this doesn't work
```javascript
class User extends bookshelf.Model {
    static get schema() {
        return [
              StringField('username'),
              EncryptedStringField("password")
        ]
   }
}
```
neither do this one

so what is the correct way to use schema in es6 classes?

**Comment by bogus34** [comment]
Hello!
'schema' should be called as a static method.

So correct way to use it is
```
class User extends bookshelf.Model {
  ... all about User model
}

User.schema([
 ... schema entities
]);
```

Actually, that's what CoffeeScript variant does.

**Comment by roackb2** [comment]
Oh I see, I digged into the code and were doing something like:
```javascript
bookshelf.Model.schema.call(User, [... schema entities]);
```
 didn't realize that I'm doing the same thing as above lol

**Comment by bogus34** [comment]
Great, then closing this.
